services:
  n8n_app:
    image: ghcr.io/damienbarnesautomations/precious-place-admin/n8n_custom:staging
    # NO workflow volume mounts here to prevent masking

  pos_frontend:
    image: ghcr.io/damienbarnesautomations/precious-place-admin/pos_frontend:staging

  ledger_frontend:
    image: ghcr.io/damienbarnesautomations/precious-place-admin/ledger_frontend:staging

  python_app:
    image: ghcr.io/damienbarnesautomations/precious-place-admin/python_app:staging

  custom_cake_frontend:
    image: ghcr.io/damienbarnesautomations/precious-place-admin/custom_cake_frontend:staging
