services:
  n8n_app:
    volumes:
      - ./n8n/n8n-workflows:/home/node/.n8n-files/workflows
      - ./custom-cake-order-manager/n8n/n8n-workflows:/home/node/.n8n-files/cake-workflows
    entrypoint: ["/bin/sh", "/home/node/.n8n-files/workflows/n8n-init/n8n-import.sh"]

  pos_frontend:
    build:
      context: ./pos-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}
        - VITE_IMAGE_BASE_URL=${IMAGE_BASE_URL}
        - VITE_CURRENCY=$
        - VITE_APP_TITLE=Precious Place POS
        - VITE_APP_ICON=/icon.png
        - VITE_LOGO=precious_place_logo-removebg.png
        - DOMAIN_OR_IP=${DOMAIN_OR_IP}
        - VITE_GET_PRODUCTS_WEBHOOK=${API_BASE_URL}pos/products
        - VITE_RECORD_SALES_WEBHOOK=${API_BASE_URL}pos/recordSales
        - VITE_DAILY_SALES_WEBHOOK=${API_BASE_URL}pos/dailyTotalSales

  ledger_frontend:
    build:
      context: ./ledger-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}
        - VITE_APP_TITLE=Accounting
        - VITE_GET_JOURNAL_ENTRIES_WEBHOOK=${API_BASE_URL}accounting/journalEntries
        - VITE_GET_ACCOUNTS_WEBHOOK=${API_BASE_URL}accounting/accounts
        - VITE_GET_GENERAL_LEDGER_WEBHOOK=${API_BASE_URL}accounting/ledger
        - VITE_GET_TRIAL_BALANCE_WEBHOOK=${API_BASE_URL}accounting/trialBalance
        - VITE_GET_CATEGORIES_WEBHOOK=${API_BASE_URL}accounting/categories
        - VITE_GET_BALANCE_SHEET_WEBHOOK=${API_BASE_URL}accounting/balanceSheet
        - VITE_GET_PROFIT_LOSS_WEBHOOK=${API_BASE_URL}accounting/profitAndLoss
        - VITE_POST_JOURNAL_ENTRIES_WEBHOOK=${API_BASE_URL}accounting/journalEntry
        - VITE_CREATE_ACCOUNT_WEBHOOK=${API_BASE_URL}accounting/createAccount
        - VITE_GET_INCOME_WEBHOOK=${API_BASE_URL}accounting/incomeReport
        - VITE_GET_EXPENSE_WEBHOOK=${API_BASE_URL}accounting/expenseReport

  python_app:
    build:
      context: ./custom-cake-order-manager/python_app
      dockerfile: Dockerfile

  custom_cake_frontend:
    build:
      context: ./custom-cake-order-manager/custom_cake_frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}
        - VITE_APP_TITLE=Custom Cake
        - VITE_IMAGE_BASE_URL=${IMAGE_BASE_URL}
        - DOMAIN_OR_IP=${DOMAIN_OR_IP}
