server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = /pos {
        return 301 /pos/;
    }

    location /pos/ {
        try_files $uri $uri/ /pos/index.html;
    }
}